<?php

namespace RaufletBundle\Repository;

/**
 * ObjectsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectsTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
