<?php

namespace RaufletBundle\Repository;

/**
 * StrongAgainstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrongAgainstRepository extends \Doctrine\ORM\EntityRepository
{
}
