<?php

namespace RaufletBundle\Repository;

/**
 * WeakAgainstRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeakAgainstRepository extends \Doctrine\ORM\EntityRepository
{
}
