<?php

namespace RaufletBundle\Repository;

/**
 * WinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinRepository extends \Doctrine\ORM\EntityRepository
{
}
